class Main {
  public static void main(String[] args) {

    // Math.rint()
    // value greater than 5 after decimal
    System.out.println(Math.rint(1.878));  // 2.0

    // value less than 5 after decimal
    System.out.println(Math.rint(1.34));   // 1.0

    // value equal to 5 after decimal
    System.out.println(Math.rint(1.5));    // 2.0

    // value equal to 5 after decimal
    System.out.println(Math.rint(2.5));    // 2.0

  }
}
